# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Eon < Formula
  desc "Cron and one-shot job scheduler that runs in-process"
  homepage "https://github.com/rednafi/eon"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/rednafi/eon/releases/download/v0.1.0/eon-v0.1.0-darwin-arm64.tar.gz"
      sha256 "604a9099a73d3c39a6956f84b9ef791d2454d3389f587855f8e65a8eead20203"

      define_method(:install) do
        bin.install "eon"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rednafi/eon/releases/download/v0.1.0/eon-v0.1.0-linux-amd64.tar.gz"
      sha256 "c49bce584f5b2e2c685c84ffea936ac51bcd7c2b0e34ff349de351386cd6c90e"
      define_method(:install) do
        bin.install "eon"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rednafi/eon/releases/download/v0.1.0/eon-v0.1.0-linux-arm64.tar.gz"
      sha256 "42b698e0f035490b58693cd3608ad1e4e6cbf3827029a7ea673ac9bec2cd40d3"
      define_method(:install) do
        bin.install "eon"
      end
    end
  end

  test do
    assert_match "eon", shell_output("#{bin}/eon --help")
  end
end
