# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Eon < Formula
  desc "Cron and one-shot job scheduler that runs in-process"
  homepage "https://github.com/rednafi/eon"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/rednafi/eon/releases/download/v0.1.2/eon-v0.1.2-darwin-arm64.tar.gz"
      sha256 "e66eb77103a04c85960df1c93af5b732274abde5f0aba766c328d4369199070a"

      define_method(:install) do
        bin.install "eon"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rednafi/eon/releases/download/v0.1.2/eon-v0.1.2-linux-amd64.tar.gz"
      sha256 "91a691cd694e2b63791b6460005656a62c6981e9da5f218b45a72cc9875d50c5"
      define_method(:install) do
        bin.install "eon"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rednafi/eon/releases/download/v0.1.2/eon-v0.1.2-linux-arm64.tar.gz"
      sha256 "e76e010a444fe9c5c11da4e60f56e3641c0372d31aa7eb63c8b33dc0c4293c12"
      define_method(:install) do
        bin.install "eon"
      end
    end
  end

  test do
    assert_match "eon", shell_output("#{bin}/eon --help")
  end
end
